from decouple import config

INGESTION_API = config("INGESTION_API")

BLOB_ACCOUNT_NAME = config("BLOB_ACCOUNT_NAME")
BLOB_ACCOUNT_KEY = config("BLOB_ACCOUNT_KEY")
BLOB_AZURE_CONNECT_STRING = f"DefaultEndpointsProtocol=https;AccountName={BLOB_ACCOUNT_NAME};AccountKey={BLOB_ACCOUNT_KEY};EndpointSuffix=core.windows.net"
BLOB_HESA_CONTAINER_NAME = config("BLOB_HESA_CONTAINER_NAME")
BLOB_HESA_BLOB_NAME = config("BLOB_HESA_BLOB_NAME")

COSMOS_DATABASE_ID = config("COSMOS_DATABASE_ID")
COSMOS_DATABASE_URI = config("COSMOS_DATABASE_URI")
COSMOS_DATABASE_KEY = config("COSMOS_DATABASE_KEY")
KEY_COSMOS_MASTER_KEY = "masterKey"

COSMOS_COLLECTION_INSTITUTIONS = config("COSMOS_COLLECTION_INSTITUTIONS")
COSMOS_COLLECTION_SUBJECTS = config("COSMOS_COLLECTION_SUBJECTS")
COSMOS_COLLECTION_COURSES = config("COSMOS_COLLECTION_COURSES")
COSMOS_COLLECTION_DATASET = config("COSMOS_COLLECTION_DATASET")

BLOB_STORAGE_URL = config("BLOB_STORAGE_URL")
STORAGE_URL = config("STORAGE_URL")

BLOB_JSON_FILES_CONTAINER_NAME = config("BLOB_JSON_FILES_CONTAINER_NAME")
BLOB_INSTITUTIONS_JSON_FILE_BLOB_NAME_EN = config("BLOB_INSTITUTIONS_JSON_FILE_BLOB_NAME_EN")
BLOB_INSTITUTIONS_JSON_FILE_BLOB_NAME_CY = config("BLOB_INSTITUTIONS_JSON_FILE_BLOB_NAME_CY")
BLOB_INSTITUTIONS_SITEMAPS_JSON_FILE_BLOB_NAME = config("BLOB_INSTITUTIONS_SITEMAPS_JSON_FILE_BLOB_NAME")
BLOB_VERSION_JSON_FILE_BLOB_NAME = config("BLOB_VERSION_JSON_FILE_BLOB_NAME")

BLOB_POSTCODES_BLOB_NAME = config("BLOB_POSTCODES_BLOB_NAME")
BLOB_POSTCODES_CONTAINER_NAME = config("BLOB_POSTCODES_CONTAINER_NAME")

BLOB_QUALIFICATIONS_BLOB_NAME = config("BLOB_QUALIFICATIONS_BLOB_NAME")
BLOB_QUALIFICATIONS_CONTAINER_NAME = config("BLOB_QUALIFICATIONS_CONTAINER_NAME")

BLOB_SUBJECTS_BLOB_NAME = config("BLOB_SUBJECTS_BLOB_NAME")
BLOB_SUBJECTS_CONTAINER_NAME = config("BLOB_SUBJECTS_CONTAINER_NAME")
BLOB_SUBJECTS_JSON_BLOB_NAME = config("BLOB_SUBJECTS_JSON_BLOB_NAME")

BLOB_WELSH_UNIS_BLOB_NAME = config("BLOB_WELSH_UNIS_BLOB_NAME")
BLOB_WELSH_UNIS_CONTAINER_NAME = config("BLOB_WELSH_UNIS_CONTAINER_NAME")

SEARCH_API_KEY = config("SEARCH_API_KEY")
SEARCH_URL = config("SEARCH_URL")
SEARCH_API_VERSION = config("SEARCH_API_VERSION")

SEND_GRID_API_KEY = config("SEND_GRID_API_KEY")
SEND_GRID_FROM_EMAIL = config("SEND_GRID_FROM_EMAIL")
SEND_GRID_TO_EMAILS = config("SEND_GRID_TO_EMAILS")

# Local test xml file is to be used for testing the pipeline locally
# defaults to None, as in production this will not be set
XML_USE_LOCAL_TEST_XML_FILE = config("XML_USE_LOCAL_TEST_XML_FILE")
XML_LOCAL_TEST_XML_FILE = config("XML_LOCAL_TEST_XML_FILE", default=None)

MINUTES_WAIT_BEFORE_CREATE_NEW_DATASET = config("MINUTES_WAIT_BEFORE_CREATE_NEW_DATASET")

POSTCODE_INDEX_NAME = config("POSTCODE_INDEX_NAME")

ENVIRONMENT = config("ENVIRONMENT")  # i.e. dev, pre-prod or prod

STOP_ETL_PIPELINE_ON_WARNING = config("STOP_ETL_PIPELINE_ON_WARNING")
