# DevOps Pipeline definition for the OFS Beta Backend Data Pipeline 

#Disable CI
trigger: none

#Disable PR
pr: none

# Build Agent Resources
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python3:
      python.version: '3.11'

# Build Process Tree
steps:

# Enforce Python Version (see above)
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'


- task: PythonScript@0
  displayName: 'Download and Process HESA Data'
  inputs:
    scriptSource: 'inline'
    script: |
      """Download the HESA zip file, extract the kis*.xml file, and prepare it for storage"""
      import urllib.request
      import time
      import gzip
      import zipfile
      import shutil
      import os
      import glob
      import tempfile

      # Set up request headers
      hdr = {
          'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
          'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
          'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
          'Accept-Encoding': 'none',
          'Accept-Language': 'en-US,en;q=0.8',
          'Connection': 'keep-alive'
      }

      # Download the file with retry logic
      url = '$(HesaURL)'
      max_retries = 3
      retry_delay = 10
      attempt = 0
      temp_dir = '$(Agent.TempDirectory)'
      zip_file_path = os.path.join(temp_dir, 'hesa_data.zip')
      extract_dir = os.path.join(temp_dir, 'extracted_data')

      # Create extraction directory if it doesn't exist
      if not os.path.exists(extract_dir):
          os.makedirs(extract_dir)

      # Download the zip file
      while attempt < max_retries:
          try:
              print(f'Attempting to fetch file from {url}... Attempt #{attempt + 1}')

              hesa_request = urllib.request.Request(url, headers=hdr)
              hesa_response = urllib.request.urlopen(hesa_request)

              print('Beginning file download...')
              with open(zip_file_path, 'wb') as f:
                  while True:
                      data = hesa_response.read(1024)
                      if not data:
                          break
                      f.write(data)

              print('Download complete!')
              break
          except Exception as e:
              print(f'Error during download attempt {attempt + 1}: {e}')
              attempt += 1
              if attempt < max_retries:
                  print(f'Retrying in {retry_delay} seconds...')
                  time.sleep(retry_delay)
              else:
                  print('Max retries reached. Failing the request.')
                  raise

      # Extract the zip file
      print('Extracting zip file...')
      try:
          # Extract all contents to the extraction directory
          with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
              zip_ref.extractall(extract_dir)
          print('Extraction complete!')
      except Exception as e:
          print(f'Error extracting zip file: {e}')
          raise

      # Find the kis*.xml file
      print('Looking for kis*.xml file...')
      kis_file_path = None

      # Search for kis*.xml in the extracted directory and subdirectories
      for root, dirs, files in os.walk(extract_dir):
          for file in files:
              if file.startswith('kis') and file.endswith('.xml'):
                  kis_file_path = os.path.join(root, file)
                  print(f'Found matching file: {kis_file_path}')
                  break
          if kis_file_path:
              break

      if not kis_file_path:
          raise Exception('No kis*.xml file found in the extracted data')

      # Create the gzipped output file
      output_file = os.path.join(temp_dir, 'latest.xml.gz')
      print(f'Creating gzipped output file: {output_file}')

      with open(kis_file_path, 'rb') as f_in:
          with gzip.open(output_file, 'wb') as f_out:
              shutil.copyfileobj(f_in, f_out)

      print('Processing complete! File ready for upload to blob storage.')


- task: AzureCLI@2
  displayName: 'Copy kis archive to storage blob'
  inputs:
    azureSubscription: '$(AzureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Install Azure CLI storage extension if not already installed
      az extension add --name storage-preview --allow-preview true --only-show-errors || true

      # Upload the file to blob storage
      az storage blob upload \
        --account-name "$(AzureStorageAccount)" \
        --container-name "$(AzureStorageBlob)" \
        --file "$(Agent.TempDirectory)/latest.xml.gz" \
        --name "latest.xml.gz" \
        --overwrite


- task: PythonScript@0
  displayName: 'Start Data Import Pipeline'
  inputs:
    scriptSource: 'inline'
    script: |
      """Send a request to the Data Import Pipeline in order to trigger it"""
      import urllib.request

      hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
      'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
      'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
      'Accept-Encoding': 'none',
      'Accept-Language': 'en-US,en;q=0.8',
      'Connection': 'keep-alive'}

      url = '$(DataPipelineURL)'

      print('Sending request to pipeline...')

      pipeline_request = urllib.request.Request(url, headers=hdr)
      pipeline_response = urllib.request.urlopen(pipeline_request, timeout=120)

      print('Request sent!')