# pre-prod-hesa-pipeline.yml
trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
- group: hesa-preprod  # Library group containing AzureSubscription, HesaURL, etc.

extends:
  template: .azuredevops/hesa-template.yml
  parameters:
    AzureSubscription: '$(AzureSubscription)'
    AzureStorageAccount: '$(AzureStorageAccount)'
    AzureStorageBlob: '$(AzureStorageBlob)'
    HesaURL: '$(HesaURL)'
    DataPipelineURL: '$(DataPipelineURL)'
    PythonVersion: '3.13'