# DevOps Pipeline definition for the OFS Beta Backend Data Pipeline 

#Disable CI
trigger: none

#Disable PR
pr: none

# Build Agent Resources
pool:
  vmImage: 'windows-latest'
strategy:
  matrix:
    Python3:
      python.version: '3.10'
      
# Build Process Tree
steps:

# Enforce Python Version (see above)
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- task: AzureCLI@2
  displayName: 'Copy kis archive to storage blob'
  inputs:
    azureSubscription: '$(AzureSubscription)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob upload \
        --account-name $(AzureStorageAccount) \
        --container-name $(AzureStorageBlob) \
        --name latest.xml.gz \
        --file $(Agent.TempDirectory)\latest.xml.gz \
        --overwrite

- task: PythonScript@0
  displayName: 'Start Data Import Pipeline'
  inputs:
    scriptSource: 'inline'
    script: |
      """Send a request to the Data Import Pipeline in order to trigger it"""
      import urllib.request

      hdr = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
      'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
      'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
      'Accept-Encoding': 'none',
      'Accept-Language': 'en-US,en;q=0.8',
      'Connection': 'keep-alive'}

      url = '$(DataPipelineURL)'

      print('Sending request to pipeline...')

      pipeline_request = urllib.request.Request(url, headers=hdr)
      pipeline_response = urllib.request.urlopen(pipeline_request, timeout=120)

      print('Request sent!')

