# prod-azure-pipelines.yml
trigger:
  - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: pipeline-prod  # Library group containing production variables

extends:
  template: .azuredevops/azure-template.yml
  parameters:
    pythonVersion: '$(PythonVersion)' # Pulls from the variable group