# prod-hesa-pipeline.yml
trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
- group: hesa-prod  # Library group containing production values

extends:
  template: .azuredevops/hesa-template.yml
  parameters:
    AzureSubscription: '$(AzureSubscription)'
    AzureStorageAccount: '$(AzureStorageAccount)'
    AzureStorageBlob: '$(AzureStorageBlob)'
    HesaURL: '$(HesaURL)'
    DataPipelineURL: '$(DataPipelineURL)'
    PythonVersion: '3.13'