version: '3'

services:
  app:
    environment:
      AzureCosmosDbCoursesCollectionId: "courses"
      AzureCosmosDbDatabaseId: "discoveruni"
      AzureCosmosDbDataSetCollectionId: "datasets"
      AzureCosmosDbInstitutionsCollectionId: "institutions"
      AzureCosmosDbKey: "xbrnDkm5zfC6lE0Rg6LYJ9dks2qvSTAQPWO3D47ub0Sua0fWFr5qlbvVf6ae4OoZpJvTvdwxzbyfNMEj9kyTig=="
      AzureCosmosDbSubjectsCollectionId: "subjects"
      AzureCosmosDbUkRlpCollectionId: "ukrlp"
      AzureCosmosDbUkRlpStaticCollectionId: "ukrlp_static"
      AzureCosmosDbUri: "https://dev-mob-discoveruni.documents.azure.com:443/"
      AzureSearchAPIVersion: "2019-05-06"
      AzureStorageAccountConnectionString: "DefaultEndpointsProtocol=https;AccountName=devdiscoveruni;AccountKey=fMNoakiDVvwAfV8+VonJreuH0OrJ0/InL6UN1+qjZdHzHVvI+UOJb2DNiLUW4BcXzP3RJV/UhvwcUuLxDQmiIA==;EndpointSuffix=core.windows.net"
      AzureStorageAccountKey: "fMNoakiDVvwAfV8+VonJreuH0OrJ0/InL6UN1+qjZdHzHVvI+UOJb2DNiLUW4BcXzP3RJV/UhvwcUuLxDQmiIA=="
      AzureStorageAccountName: "devdiscoveruni"
      AzureStorageHesaBlobName: "latest.xml.gz"
      AzureStorageHesaContainerName: "hesa-raw-xml-ingest"
      AzureStoragePostcodesBlobName: "postcode.json.gz"
      AzureStoragePostcodesContainerName: "postcodes"
      AzureStorageQualificationsContainerName: "qualifications"
      AzureStorageQualificationsBlobName: "qualification-levels.csv.gz"
      AzureStorageSubjectsBlobName: "english-and-welsh-subject-names.csv.gz"
      AzureStorageSubjectsContainerName: "subjects"
      AzureStorageSubjectsJSONFileBlobName: "subjects.json"
      AzureStorageInstitutionsENJSONFileBlobName: "institutions_en.json"
      AzureStorageInstitutionsCYJSONFileBlobName: "institutions_cy.json"
      AzureStorageJSONFilesContainerName: "jsonfiles"
      AzureStorageWelshUnisBlobName: "welsh-institution-names.csv.gz"
      AzureStorageWelshUnisContainerName: "welsh-unis"
      AzureWebJobsCourseSearchBuilder.Disabled": "false"
      AzureWebJobsCreateDataSet.Disabled": "false"
      AzureWebJobsCreateInst.Disabled": "false"
      AzureWebJobsCreateUkrlp.Disabled": "false"
      AzureWebJobsEtlPipeline.Disabled": "false"
      AzureWebJobsPostcodeSearchBuilder.Disabled": "true"
      AzureWebJobsSubjectBuilder.Disabled": "false"
      AzureWebJobsStorage: "DefaultEndpointsProtocol=https;AccountName=devdiscoveruni;AccountKey=fMNoakiDVvwAfV8+VonJreuH0OrJ0/InL6UN1+qjZdHzHVvI+UOJb2DNiLUW4BcXzP3RJV/UhvwcUuLxDQmiIA==;EndpointSuffix=core.windows.net"
      Environment: "Development"
      FUNCTIONS_WORKER_RUNTIME: "python"
      SearchAPIKey: "D7F2503A43F97BEA5DE101B0409F3558"
      SearchURL: "https://dev-course-search.search.windows.net"
      SendGridAPIKey: "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"
      SendGridEnabled: "False"
      SendGridFromEmail: "DiscoverUniAutomation@officeforstudents.org.uk"
      SendGridFromName: "DiscoveruniAutomation"
      SendGridToEmailList: "robert.rokosz@mobilise.cloud"
      StopEtlPipelineOnWarning: "false"
      StorageUrl: "https://devdiscoveruni.blob.core.windows.net/"
      TimeInMinsToWaitBeforeCreateNewDataSet: "1"
      UkRlpOfsId: "9"
      UkRlpUrl: "http://webservices.ukrlp.co.uk/UkrlpProviderQueryWS5/ProviderQueryServiceV5"
      UseLocalTestXMLFile: "true"
      LocalTestXMLFile: "rob_1_course.xml"
    build: .
    command: bash -c "python institutions_output.py"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
